# Generated by Django 5.1.1 on 2024-09-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_coffeeathome_drink_food_merchandise_readytoeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='kcal',
        ),
    ]
