# Generated by Django 5.1.1 on 2024-09-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_remove_merchandise_kcal'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='kcal',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
