# Generated by Django 5.1.1 on 2024-09-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_merchandise_kcal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
