# Generated by Django 5.1.1 on 2024-09-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='veg',
            field=models.BooleanField(default=False),
        ),
    ]
