# Generated by Django 5.1.1 on 2024-09-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_food_veg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='veg',
            new_name='nonVeg',
        ),
    ]
