# Generated by Django 5.1.1 on 2024-09-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_coffeecart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeecart',
            name='email',
        ),
    ]
